version: "3.4"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - mongodb
      - redisdb
    networks:
      - makentu-web
      - nginx
  mongodb:
    image: mongo
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eeinfo
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - makentu-web
  redisdb:
    image: redis
    expose:
      - "6379"
    networks:
      - makentu-web
networks:
  nginx:
    external: true
  makentu-web:
