# This file is used for development, not for production!

version: "3.4"

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eeinfo
      - MONGO_INITDB_ROOT_PASSWORD=password

  redisdb:
    image: redis
    ports:
      - "6379:6379"
